### ISSUE TITLE
DIS: charm pdf in F3charm at CC

### ISSUE THREAD

**Issue by felixhekhorn** [scarrazza/apfel#26]
- We believe there is a bug in combination of CC coefficient functions with the respective PDFs
- When computing `F3charm` with the `conly` pdf (which is defined by `c(x)=x(1-x)` and 0 otherwise ) APFEL is 0, while we're not (see table below)
- looking at the PDG expression for the LO expressions (=parton-model) the charm pdf can contribute to F3 when scattering electrons or anti-neutrinos (what we are doing here) (see also Eq. 51 of `CC_observables_def.pdf`)
- keep in mind that the APFEL definition of `F3charm` relies on the seperation of the CKM matrix

output:
```
------------------------------F3charm------------------------------

           x           Q2  APFEL    yadism  yadism_error  rel_err[%]
0   0.000317    90.000000    0.0  0.001465  6.438219e-12         inf
1   0.001007    90.000000    0.0  0.003751  9.234736e-12         inf
2   0.003195    90.000000    0.0  0.009510  4.041613e-11         inf
3   0.010138    90.000000    0.0  0.024013  1.321150e-10         inf
4   0.032169    90.000000    0.0  0.060758  4.250026e-10         inf
5   0.102077    90.000000    0.0  0.153750  1.063813e-09         inf
6   0.304545    90.000000    0.0  0.346403  1.647991e-09         inf
7   0.536364    90.000000    0.0  0.450932  2.779282e-09         inf
8   0.768182    90.000000    0.0  0.395607  6.832703e-10         inf
9   1.000000    90.000000    0.0  0.000000  0.000000e+00         NaN
10  0.001000     4.000000    0.0  0.008233  9.639907e-12         inf
11  0.001000     7.387505    0.0  0.005930  2.837073e-11         inf
12  0.001000    13.643806    0.0  0.004952  1.346871e-11         inf
13  0.001000    25.198421    0.0  0.004389  1.252950e-11         inf
14  0.001000    46.538363    0.0  0.004015  1.220218e-11         inf
15  0.001000    85.950595    0.0  0.003747  1.481200e-11         inf
16  0.001000   158.740105    0.0  0.003545  1.100350e-11         inf
17  0.001000   293.173318    0.0  0.003386  1.215494e-11         inf
18  0.001000   541.454816    0.0  0.003258  1.348017e-11         inf
19  0.001000  1000.000000    0.0  0.003152  1.028605e-11         inf
--------------------------------------------------------------------
```
APFEL setup:
```
   
 WARNING: FFNS is a FFN scheme
          ... setting NF = 3 FFNS PDF evolution
 WARNING: if there are external grids they cannot be locked
          ... unlocking subgrids
 
 Welcome to 
      _/_/_/    _/_/_/_/   _/_/_/_/   _/_/_/_/   _/
    _/    _/   _/    _/   _/         _/         _/
   _/_/_/_/   _/_/_/_/   _/_/_/     _/_/_/     _/
  _/    _/   _/         _/         _/         _/
 _/    _/   _/         _/         _/_/_/_/   _/_/_/_/
 _____v3.0.4 A PDF Evolution Library, arXiv:1310.1394
      Authors: V. Bertone, S. Carrazza, J. Rojo
 
 Report of the evolution parameters:
   
 QCD evolution
 Space-like evolution (PDFs)
 Unpolarized evolution
 Evolution scheme: FFNS with 3 active flavours at N1LO
 Solution of the DGLAP equation: 'exactalpha'
 Solution of the coupling equations: 'exact'
 Coupling reference value:
 - AlphaQCD( 91.2000 GeV) =  0.118000
 Pole heavy quark masses:
 - Mc =   2.0000 GeV
 - Mb =   4.0000 GeV
 - Mt = 173.0700 GeV
 The matching thresholds coincide with the physical masses
 muR / muF =  1.0000
  
 Allowed evolution range [   1.0000 :  10000.0000 ] GeV
 Fast evolution enabled
 
 Initialization of the evolution completed in   1.309 s
  
 Report of the electroweak parameters:
   
 Mass of the Z = 91.188 GeV
 Mass of the W = 80.398 GeV
 Mass of the proton = 0.9380 GeV
 sin^2(thetaW) = 0.2313
 GFermi = 1.16638E-05
       | 0.9743 0.2253 0.0035 |
 CKM = | 0.2252 0.9735 0.0410 |
       | 0.0086 0.0403 0.9992 |
 Z propagator correction = 0.00000
   
 Report of the DIS parameters:
   
 Computation in the FFNS3 mass scheme
 Charged Current (CC) process
 Scattering electron - proton   
 muR / Q =  0.5000
 muF / Q =  1.0000
 (No scale variation in the evolution)
 Target Mass corrections disabled
 Intrinsic charm disabled
```

**Comment by juanrojochacon** [comment]
In your model conly is charm the same as anticharm or different? I am confused here

**Comment by felixhekhorn** [comment]
>  according to the PDF, Eq. (18.18), 

are we talking about the same file? we meant this one: https://github.com/scarrazza/apfel/blob/master/doc/pdfs/CC_observables_def.pdf and there seems to be no equation (18.18)

> And we never have a non-zero charm asymmetry, at least at the input evolution scale

maybe in a true physical setup, yes, but here we think of the PDF as an external property (of which we know nothing) (and also c and cbar can diverge at higher orders) ... so here for benchmarking purpose to isolate one feature from another, we've chosen the (unphysical) `conly` with

> In your model conly is charm the same as anticharm or different?

`c=x(1-x), cbar=0=u=ubar=g=...`

**Comment by juanrojochacon** [comment]
I meant the PDG ;)

It is true that for benchmarking purposes we can assume that c and cbar are different (although this will not happen in a realistic setup). In this case yes, APFEL should return a non-zero value, I agree. So this needs to be fixed, I guess that somewhere in APFEL one assumes that c_V=0?

**Comment by vbertone** [comment]
@felixhekhorn from the banner I see that you are using the NF = 3 FFNS that assumes that there is no charm in the initial state. Therefore it is perfectly consistent that you get zero.

**Comment by felixhekhorn** [comment]
> @felixhekhorn from the banner I see that you are using the NF = 3 FFNS that assumes that there is no charm in the initial state. Therefore it is perfectly consistent that you get zero.

I guess you're right -> it is a bug in *our* implementation
