### ISSUE TITLE
EVOL: VFNS with scale variations

### ISSUE THREAD

**Issue by giacomomagni** [scarrazza/apfel#37]
Dear @vbertone,
while doing our usual benchmarks with the [LHA tables](https://arxiv.org/pdf/hep-ph/0511119.pdf) and EKO, we noticed that there is a discrepancy between Apfel and the reported values in case of NNLO with scale variations. 
We believe that this is due to the strong coupling at the the threshold scale, which is not computed correctly. 
In particular [here](https://github.com/scarrazza/apfel/blob/532b77ca9f99863134179705e66305150429ad46/src/Evolution/a_QCD.f#L702-L703), we propose the change:

```
asthUp(inf)   = a_QCD(  m2th(inf) * ( 1d0 + eps ) )
asthDown(inf) = a_QCD(  m2th(inf) * ( 1d0 - eps ) )
```
Since `a_QCD` takes factorization scales as input and `m2th(inf)` are already in factorization scales.
With this fix, we are able to find good agreement.

**Comment by vbertone** [comment]
Hi @giacomomagni,
yes, this is definitely a bug.
I'm going to fix it straight away.
Thanks for spotting it.
